name: CodeDocify Docs Deployment
on:
  push:
    branches: [master]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          mkdir -p public

      - name: Copy Files
        run: |
          cp -r ././README.md public/README.md

      - name: Generate Documentation
        run: |
          echo "codo.ractstudio.com" > public/CNAME

      # - name: Index Search
      #   run: |
      #     node ./search/indexBuilder.js
      #     node ./search/algoliaUploader.js
      #   env:
      #       APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      #       ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: doc
          keep_files: true