name: CodeDocify Docs Deployment
on:
  push:
    branches: [master]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          mkdir -p public

      - name: Copy Files
        run: |
          cp -r ././README.md public/README.md

      - name: Generate Documentation
        run: |
          echo "codo.ractstudio.com" > public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: doc
          keep_files: true